### ISSUE TITLE
Can I Read/Write Anchor Names Somehow?

### ISSUE THREAD

**Issue by andrejohansson** [xoofx/SharpYaml#34]
I want to be able to control the names of anchors being emitted, more specifically:

1. How do I control the output name of an anchor?
2. How can I get the anchor name after dezerialisation?

```csharp
public class MyNode
{
  public string Name { get; set; }
  public string  MyScalar { get; set; }
}

public class MyNodeList
{
  public IList<MyNode> Items { get; set; }
}

var node = new MyNode 
{
  [YamlAnchor] // this attribute doesn´t exist, but is there something similar?
  Name = "i_want_this_to_be_the_anchor_name",
  MyScalar = "hello"
};

var list = new MyNodeList() {
  node,
  node,
  node,
  node
}
```

How can I get this:

```yaml
MyNode:
  - &i_want_this_to_be_the_anchor_name
    Name: some_name
    MyScalar: hello

Items:
  - *i_want_this_to_be_the_anchor_name
  - *i_want_this_to_be_the_anchor_name
  - *i_want_this_to_be_the_anchor_name
  - *i_want_this_to_be_the_anchor_name
```

instead of this:
```yaml
MyNode:
  - &o2
    Name: some_name
    MyScalar: hello

Items:
  - *o2
  - *o2
  - *o2
  - *o2
```
