### ISSUE TITLE
Can you get a node by using a string path somehow?

### ISSUE THREAD

**Issue by KarlOfDuty** [xoofx/SharpYaml#60]
Such as "category.object.parameter" retrieving the node at
```yaml
category:
    object:
        parameter: "hello"
```

In all other YAML libraries I've used in other languages one can get a node by simply entering the path to it as a string in a get function, is there a feature like that here?
