### ISSUE TITLE
Preserving comments

### ISSUE THREAD

**Issue by Trojaner** [xoofx/SharpYaml#85]
Is it possible to update an existing yaml file while preserving comments at the same time?

We currently need this for [OpenMod](https://github.com/openmod/openmod) (OpenMod is a free and open source plugin framework). Sometimes we add new options to the config yamls. These need to be merged to the current user configs but we would like to preserve comments. Currently we use YamlDotNet which can't do this and the authors of it don't appear to be interested into adding this either. 

**Example use case**
1. User installs OpenMod and the following yaml gets created:
```yaml
rcon:
   # Some long comment that describe what bind does and why it is set like that
   bind: 0.0.0.0
   enabled: true
```
2. An OpenMod update adds a new "rcon:port" option with 1554 as default value
3. The yaml file gets updated while preserving comments:
```yaml
rcon:
   # Some long comment that describe what bind does and why it is set like that
   bind: 0.0.0.0
   port: 1554
   enabled: true
```
